install now has an optional --core flag to only install needed packages

diff --git a/.local/bin/setup/install b/.local/bin/setup/install
--- a/.local/bin/setup/install
+++ b/.local/bin/setup/install
@@ -1,4 +1,36 @@
 #!/usr/bin/env bash
+usage="NAME
+      install - install dotfiles project
+
+SYNOPSIS
+      install [-h] [-p|--core]
+
+ARGUMENTS
+
+       -c|--core
+          Only install core packages from arch and aur.
+"
+
+while test $# -gt 0; do
+	  case "$1" in
+        -h|--help|-\?)
+            echo "$usage" >&2
+            exit
+            ;;
+        -c|--core|-\?)
+            core=true
+            shift
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        *)
+            break
+    esac
+    shift
+done
+
 
 ## update pacman
 sudo pacman -Syu --noconfirm
@@ -59,7 +91,6 @@ common_pacman_packages="
     ncurses
     fftw
     mirage
-    gvim
     groovy
 "
 
@@ -110,37 +141,48 @@ rustup install stable
 rustup default stable
 ## END RUST
 
-## install aur packages
-export aur_packages="
-  awesome-terminal-fonts
-  i3-gaps-next-git
-  xorg-xprop
-  hipchat
-  gtk-theme-arc-git
-  paper-icon-theme-git
-  spotify
-  ccat
-  exa-git
-  dropbox
-  rtv
-  dunstify
-  siji-git
-  xorg-xset
-  bashmount
-  remmina-plugin-rdesktop
-  trizen
-  polybar-git
-  pgadmin4
-  cli-visualizer
-  slack-desktop
-  slack-term
-  teams-for-linux
+core_aur_packages="
+    i3-gaps-next-git
+    xorg-xprop
+    paper-icon-theme-git
+    ccat
+    exa
+    dunstify
+    bashmount
+    trizen
+    polybar
 "
-
-
-for aur_package in $aur_packages; do
-    trizen -S --needed $aur_package --noconfirm --noedit
-done
+if [[ $core != true ]]; then
+    ## install aur packages
+    aur_packages="
+        awesome-terminal-fonts
+        i3-gaps-next-git
+        xorg-xprop
+        hipchat
+        gtk-theme-arc-git
+        paper-icon-theme-git
+        spotify
+        ccat
+        exa
+        dropbox
+        rtv
+        dunstify
+        siji-git
+        xorg-xset
+        bashmount
+        remmina-plugin-rdesktop
+        trizen
+        polybar
+        pgadmin4
+        cli-visualizer
+        slack-desktop
+        slack-term
+        teams-for-linux
+"
+    for aur_package in $aur_packages; do
+        trizen -S --needed $aur_package --noconfirm --noedit
+    done
+fi
 exit
 
 
